import type { SyntheticBillingScenario } from "./types";

export const syntheticBillingScenarios: SyntheticBillingScenario[] = [
  {
    id: "BILL-DEMO-2001",
    kind: "upgrade_entitlement_mismatch",
    customerId: "cus_demo_upgrade",
    subscription: {
      id: "sub_demo_upgrade",
      status: "active",
      plan: "pro",
      cancelAtPeriodEnd: false,
      currentPeriodEnd: "2026-09-16T00:00:00Z",
      latestInvoiceId: "in_demo_upgrade",
    },
    payment: {
      id: "pi_demo_upgrade",
      status: "succeeded",
      amountCents: 4900,
      currency: "usd",
    },
    invoice: {
      id: "in_demo_upgrade",
      status: "paid",
      amountDueCents: 4900,
      hostedInvoiceUrl: "https://example.invalid/invoice/in_demo_upgrade",
    },
    refund: { status: "none" },
    dispute: { status: "none" },
    applicationEntitlement: "starter",
    notes: ["Synthetic payment succeeded", "Synthetic app entitlement has not caught up to subscription state"],
  },
  {
    id: "BILL-DEMO-2002",
    kind: "payment_failed",
    customerId: "cus_demo_failed",
    subscription: {
      id: "sub_demo_failed",
      status: "past_due",
      plan: "pro",
      cancelAtPeriodEnd: false,
      currentPeriodEnd: "2026-09-16T00:00:00Z",
      latestInvoiceId: "in_demo_failed",
    },
    payment: {
      id: "pi_demo_failed",
      status: "failed",
      amountCents: 4900,
      currency: "usd",
      failureReason: "card_declined",
    },
    invoice: {
      id: "in_demo_failed",
      status: "open",
      amountDueCents: 4900,
    },
    refund: { status: "none" },
    dispute: { status: "none" },
    applicationEntitlement: "pro",
    notes: ["Synthetic invoice remains open", "No payment-method mutation is permitted from the support automation"],
  },
  {
    id: "BILL-DEMO-2003",
    kind: "cancel_at_period_end",
    customerId: "cus_demo_cancel",
    subscription: {
      id: "sub_demo_cancel",
      status: "active",
      plan: "pro",
      cancelAtPeriodEnd: true,
      currentPeriodEnd: "2026-08-31T23:59:59Z",
      latestInvoiceId: "in_demo_cancel",
    },
    payment: {
      id: "pi_demo_cancel",
      status: "succeeded",
      amountCents: 4900,
      currency: "usd",
    },
    invoice: {
      id: "in_demo_cancel",
      status: "paid",
      amountDueCents: 4900,
    },
    refund: { status: "none" },
    dispute: { status: "none" },
    applicationEntitlement: "pro",
    notes: ["Synthetic subscription is scheduled to cancel at period end", "Access remains aligned with the active paid period"],
  },
  {
    id: "BILL-DEMO-2004",
    kind: "reactivated",
    customerId: "cus_demo_reactivate",
    subscription: {
      id: "sub_demo_reactivate",
      status: "active",
      plan: "team",
      cancelAtPeriodEnd: false,
      currentPeriodEnd: "2026-09-16T00:00:00Z",
      latestInvoiceId: "in_demo_reactivate",
    },
    payment: {
      id: "pi_demo_reactivate",
      status: "succeeded",
      amountCents: 9900,
      currency: "usd",
    },
    invoice: {
      id: "in_demo_reactivate",
      status: "paid",
      amountDueCents: 9900,
    },
    refund: { status: "none" },
    dispute: { status: "none" },
    applicationEntitlement: "team",
    notes: ["Synthetic cancellation flag has been cleared", "Subscription and application entitlement agree"],
  },
  {
    id: "BILL-DEMO-2005",
    kind: "invoice_request",
    customerId: "cus_demo_invoice",
    subscription: {
      id: "sub_demo_invoice",
      status: "active",
      plan: "starter",
      cancelAtPeriodEnd: false,
      currentPeriodEnd: "2026-09-16T00:00:00Z",
      latestInvoiceId: "in_demo_invoice",
    },
    payment: {
      id: "pi_demo_invoice",
      status: "succeeded",
      amountCents: 1900,
      currency: "usd",
    },
    invoice: {
      id: "in_demo_invoice",
      status: "paid",
      amountDueCents: 1900,
      hostedInvoiceUrl: "https://example.invalid/invoice/in_demo_invoice",
    },
    refund: { status: "none" },
    dispute: { status: "none" },
    applicationEntitlement: "starter",
    notes: ["Synthetic invoice is paid and available for guidance", "The demo URL is intentionally non-routable"],
  },
  {
    id: "BILL-DEMO-2006",
    kind: "refund_request",
    customerId: "cus_demo_refund",
    subscription: {
      id: "sub_demo_refund",
      status: "active",
      plan: "pro",
      cancelAtPeriodEnd: false,
      currentPeriodEnd: "2026-09-16T00:00:00Z",
      latestInvoiceId: "in_demo_refund",
    },
    payment: {
      id: "pi_demo_refund",
      status: "succeeded",
      amountCents: 4900,
      currency: "usd",
    },
    invoice: {
      id: "in_demo_refund",
      status: "paid",
      amountDueCents: 4900,
    },
    refund: { status: "requested" },
    dispute: { status: "none" },
    applicationEntitlement: "pro",
    notes: ["Synthetic customer requested a refund", "No refund has been executed"],
  },
  {
    id: "BILL-DEMO-2007",
    kind: "dispute_chargeback",
    customerId: "cus_demo_dispute",
    subscription: {
      id: "sub_demo_dispute",
      status: "active",
      plan: "team",
      cancelAtPeriodEnd: false,
      currentPeriodEnd: "2026-09-16T00:00:00Z",
      latestInvoiceId: "in_demo_dispute",
    },
    payment: {
      id: "pi_demo_dispute",
      status: "succeeded",
      amountCents: 9900,
      currency: "usd",
    },
    invoice: {
      id: "in_demo_dispute",
      status: "paid",
      amountDueCents: 9900,
    },
    refund: { status: "none" },
    dispute: {
      id: "dp_demo_dispute",
      status: "needs_response",
    },
    applicationEntitlement: "team",
    notes: ["Synthetic chargeback is awaiting a specialist response", "Automation must not resolve or concede the dispute"],
  },
];

export function findSyntheticBillingScenario(id: string | undefined): SyntheticBillingScenario | undefined {
  if (!id) return undefined;
  return syntheticBillingScenarios.find((scenario) => scenario.id === id);
}
